services:
  fastapi:
    container_name: kadai_fastapi
    build: Backend/
    ports:
      - 9004:9004
    volumes:
      - ./Backend/src:/src
    working_dir: /src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - mysql

  php:
    container_name: kadai_php
    image: php:8.2-apache
    ports:
      - 8500:80
    volumes:
      - ./Frontend/src:/var/www/html
      - ./Frontend/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./Frontend/frontend.env
    depends_on:
      - mysql

  mysql:
      image: mysql:8.0
      container_name: kadai_mysql
      volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      expose:
      - 3306
      environment:
        - MYSQL_DATABASE=kadai
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
        - TZ=Asia/Tokyo
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kadai_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 8081:80
    depends_on:
      - mysql

  # cloudflared:
  #   image: cloudflare/cloudflared
  #   container_name: kadai_cloudflared
  #   command: tunnel run
  #   env_file:
  #     - compose.env