FROM python:3.11.8-slim

RUN mkdir /src
WORKDIR /src

RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && apt-get clean

COPY requirements.txt /src

RUN pip install --no-cache-dir -r requirements.txt